### ISSUE TITLE
Where to swipe?

### ISSUE THREAD

**Issue by Magneticdud** [jonashellmann/mobile-gestures#1]
I am using Firefox for android.

I am swiping everywhere, but i see no effect.

I can swipe everywhere in the screen?

**Comment by jonashellmann** [comment]
Hey,

it should be possible to swip anywhere on the display. In order for the gesture to be recognized, you must move your finger across the screen at least 140px, which is less than half the screen width for mobile phones. 

I can think of a few things that might be a problem:
1. The add-on does not work on *.mozilla.org sites because the Firefox API is disabled on these sites. Try it for example on google.com.
2. Since the latest version, gestures are customizable. It is possible that the initial settings were not set during installation. To check this, go to Menu -> Add-ons -> Mobile Gestures to open the settings of the add-on and check whether the text fields are filled. Even if they are prefilled, save them at the bottom of the page and try again. Otherwise you can type in the gestures. Example: RDLU for right -> down -> left -> up.
3. Open the page "about:firefox" and check the Firefox version. This should be 54 or more current.
4. Did you download the add-on from Mozilla's Add-on Store (https://addons.mozilla.org/de/firefox/addon/mobile-gestures/)?

I hope I've been able to help you with this.
If not, I might be able to test an installation of the add-on on another mobile phone in the next few days.

Many greetings
Jonas

**Comment by Magneticdud** [comment]
I was trying the addon on the extension page (Mozilla domain) because of the list of shortcuts, that's why it did not work

Thanks. On other pages it works
